// internal/loop/api/ws_stream.go
//
// Phase 6d-c'-A: WebSocket read path for
// `/v1/sessions/:id/stream` (plan §3.1 "保留现有
// GET /v1/sessions/:sessionId/stream 作为低层 fanout").
//
// Why this file exists:
//
//   The default read path is HTTP `waitForEvent` long polling
//   (6c / wait_tick.go). 6d-c'-A adds an opt-in alternative:
//   the client opens a WebSocket to the per-session stream
//   endpoint and reads pushed events line-by-line. The shape
//   mirrors `WaitForEvents`'s output so the caller's
//   handleWsReadEvent can be structurally identical to
//   handleWaitDone — same transcript append, same
//   LastEventRev advance, same trim.
//
// Wire contract (minimum, server may extend):
//
//	GET ws://host/v1/sessions/:sessionId/stream?since=<rev>
//	< 101 Switching Protocols
//	< server pushes one JSON object per line, each carrying
//	  a `type` field (same taxonomy as `waitForEvents` events:
//	  user_prompt / assistant_text / tool_completed /
//	  scope_boundary_* / permission_request / etc.) plus
//	  the event payload. A "rev" field on each event marks
//	  the new LastEventRev.
//
// The client is defensive: Dial errors fall back to the HTTP
// wait path (caller is responsible for choosing the
// alternative). The stream loop reads until ctx is cancelled
// or the socket returns a permanent error (close frame or
// repeated read errors) and then closes the channel.
//
// This file does NOT add a WS write path — 6d-c'-B is
// reserved for `submit / approve / deny / cancel` over WS.

package api

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

// newRequestID returns a fresh request-id for
// CommandRequest. 8 bytes of crypto/rand + a nanosecond
// timestamp is overkill for correlation but cheap; the
// requestId is opaque to the server and only used by the
// client to match a CommandResponse to its in-flight
// CommandRequest.
func newRequestID() string {
	var buf [8]byte
	_, _ = rand.Read(buf[:])
	return fmt.Sprintf("%d-%s", time.Now().UnixNano(), hex.EncodeToString(buf[:]))
}

// StreamEvent is one server-pushed event over the WS
// stream. The `Rev` field is the new LastEventRev the
// client should advance to; the rest of the payload is
// passed through to the wait/WS handler as a
// `json.RawMessage` so the routing logic
// (`routeWaitEventToPane` / `EventToTranscriptItem` /
// `EventToPermission`) doesn't care whether the event
// came from HTTP or WS.
type StreamEvent struct {
	Type string          `json:"type"`
	Rev  int64           `json:"rev"`
	Raw  json.RawMessage `json:"-"`
}

// CommandAction enumerates the write actions the
// 6d-c'-B client sends over the WS write path. The
// server maps each action to the existing HTTP route:
//   - "submit"     → POST /v1/execute
//   - "approve"    → POST /v1/sessions/:id/approve
//   - "deny"       → POST /v1/sessions/:id/deny
//   - "cancel"     → POST /v1/sessions/:id/cancel
// Using a single action enum keeps the wire shape
// consistent across actions and lets the server-side
// protocol handler stay a single switch statement.
type CommandAction string

const (
	CommandSubmit  CommandAction = "submit"
	CommandApprove CommandAction = "approve"
	CommandDeny    CommandAction = "deny"
	CommandCancel  CommandAction = "cancel"
)

// CommandRequest is the client → server frame shape for
// a single write. `RequestID` is generated by the
// client (timestamp + nonce); the server echoes it on
// the response so the client can correlate a single
// response to a single in-flight request even when
// multiple commands are pending (e.g. the operator
// presses Esc + Y within 100ms — both fire concurrent
// cancel + approve requests).
type CommandRequest struct {
	Type      string          `json:"type"` // always "command"
	RequestID string          `json:"requestId"`
	Action    CommandAction   `json:"action"`
	SessionID string          `json:"sessionId"`
	Payload   json.RawMessage `json:"payload,omitempty"`
}

// CommandResponse is the server → client reply for one
// CommandRequest. `OK=false` carries an error message
// the client surfaces as a toast. On success, `Result`
// is the server's JSON response payload (the same shape
// the HTTP route would return).
type CommandResponse struct {
	Type      string          `json:"type"` // always "command_response"
	RequestID string          `json:"requestId"`
	OK        bool            `json:"ok"`
	Error     string          `json:"error,omitempty"`
	Result    json.RawMessage `json:"result,omitempty"`
}

// StreamOptions configures a per-session WS read.
type StreamOptions struct {
	// Since is the LastEventRev the server should start
	// streaming from. The server replays any events
	// with rev > Since in the same shape as waitForEvents.
	Since int64
	// DialTimeout caps the initial WebSocket Dial. 0
	// means use DefaultStreamDialTimeout.
	DialTimeout time.Duration
	// ReadTimeout caps each individual read. 0 means
	// block until the next event arrives. The
	// recommended value for production is 0 (let the
	// server push) — ReadTimeout > 0 is for tests
	// that need to surface a "no events arrived"
	// signal.
	ReadTimeout time.Duration
}

// DefaultStreamDialTimeout is the per-stream Dial
// budget. 5s matches health_tick's per-call HTTP
// timeout so a downed WS endpoint doesn't stall the
// startup path for longer than the HTTP path would.
const DefaultStreamDialTimeout = 5 * time.Second

// StreamSession opens a WebSocket to
// `/v1/sessions/:sessionId/stream?since=N` and returns
// three channels:
//
//   - events: each StreamEvent the server pushes
//   - errs:    any dial / read / close error (after which
//              the caller should fall back to HTTP wait)
//   - close:   func() the caller MUST invoke to cancel
//              the read loop and close the socket
//
// The function returns an error on Dial failure so the
// caller can decide between abort and fallback. Once
// the connection is established, all subsequent failures
// flow through the errs channel (the caller's loop
// selects on it).
//
// StreamSession never panics. The caller is responsible
// for invoking `close` exactly once.
func (c *Client) StreamSession(ctx context.Context, sessionID string, opts StreamOptions) (<-chan StreamEvent, <-chan error, func(), error) {
	if c == nil {
		return nil, nil, nil, errors.New("StreamSession: nil client")
	}
	if sessionID == "" {
		return nil, nil, nil, errors.New("StreamSession: empty sessionID")
	}
	dialTimeout := opts.DialTimeout
	if dialTimeout <= 0 {
		dialTimeout = DefaultStreamDialTimeout
	}

	// Build the ws:// URL from the client's base. c.baseURL
	// is the HTTP base; we swap http(s) → ws(s) so the
	// caller doesn't have to plumb a second config.
	u, err := url.Parse(c.BaseURL)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("StreamSession: parse base url: %w", err)
	}
	switch u.Scheme {
	case "http":
		u.Scheme = "ws"
	case "https":
		u.Scheme = "wss"
	case "ws", "wss":
		// already a WS URL — keep as-is
	default:
		return nil, nil, nil, fmt.Errorf("StreamSession: unsupported base url scheme %q", u.Scheme)
	}
	u.Path = "/v1/sessions/" + sessionID + "/stream"
	q := u.Query()
	if opts.Since > 0 {
		q.Set("since", fmt.Sprintf("%d", opts.Since))
	}
	u.RawQuery = q.Encode()

	dialCtx, cancel := context.WithTimeout(ctx, dialTimeout)
	defer cancel()

	dialer := *websocket.DefaultDialer
	dialer.HandshakeTimeout = dialTimeout
	conn, resp, err := dialer.DialContext(dialCtx, u.String(), http.Header{
		"User-Agent": []string{"bbl-loop/6d-c'-A"},
	})
	if err != nil {
		if resp != nil {
			return nil, nil, nil, fmt.Errorf("StreamSession: dial %s: %w (status %d)", u.String(), err, resp.StatusCode)
		}
		return nil, nil, nil, fmt.Errorf("StreamSession: dial %s: %w", u.String(), err)
	}

	events := make(chan StreamEvent, 16)
	errs := make(chan error, 1)

	// closeOnce ensures the close func is idempotent so
	// the caller can call it from multiple paths without
	// panicking on a double-close. The deferred close
	// in the reader goroutine uses the same guard so
	// the two close paths can't race.
	var once sync.Once
	closeChannels := func() {
		once.Do(func() {
			_ = conn.WriteControl(websocket.CloseMessage,
				websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""),
				time.Now().Add(time.Second))
			_ = conn.Close()
			close(events)
		})
	}
	closeFn := closeChannels

	// Reader goroutine: the only goroutine spawned by
	// this file. We avoid the bare-goroutine antipattern
	// at the loop package level by keeping the goroutine
	// scoped to this one function and exposing control
	// via channels + a single close func — the loop
	// runtime doesn't need to know it's there.
	go func() {
		defer closeChannels()
		for {
			// ReadMessage respects conn.SetReadDeadline;
			// we set a soft deadline only when the
			// caller asked for a ReadTimeout.
			if opts.ReadTimeout > 0 {
				_ = conn.SetReadDeadline(time.Now().Add(opts.ReadTimeout))
			}
			_, raw, err := conn.ReadMessage()
			if err != nil {
				// Surface the error and stop. The
				// caller's select on `errs` will
				// see it.
				select {
				case errs <- err:
				default:
				}
				return
			}
			var ev StreamEvent
			if err := json.Unmarshal(raw, &ev); err != nil {
				// Malformed event — log to errs but
				// keep reading. The server may
				// recover on the next push.
				select {
				case errs <- fmt.Errorf("ws stream: malformed event: %w", err):
				default:
				}
				continue
			}
			ev.Raw = raw
			select {
			case events <- ev:
			case <-ctx.Done():
				return
			}
		}
	}()

	return events, errs, closeFn, nil
}

// SendCommand is the 6d-c'-B write path. It dials a
// short-lived WebSocket to
// `/v1/sessions/:sessionId/command?action=<action>`,
// sends one CommandRequest frame, reads one
// CommandResponse, and closes. The dial is short-lived
// (single round-trip) so the surface is much simpler
// than StreamSession — no read loop, no channel
// registry, no cancel plumbing beyond ctx.
//
// Wire protocol (minimum, server may extend):
//
//	GET ws://host/v1/sessions/:sessionId/command?action=submit
//	< 101 Switching Protocols
//	> {"type":"command","requestId":"...","action":"submit","sessionId":"...","payload":{...}}
//	< {"type":"command_response","requestId":"...","ok":true,"result":{...}}
//	> server closes the socket (we close after receiving
//	  the response)
//
// The HTTP fallback paths (SubmitPrompt /
// ApprovePermission / DenyPermission / CancelSession)
// stay the default. SendCommand is the opt-in path the
// call sites pick when `useWsWrite` is true; failure to
// dial (server doesn't yet speak WS write, dial
// timeout) returns a non-nil error so the caller can
// fall back to the HTTP path without the operator
// seeing a "WS write failed" toast for every action.
func (c *Client) SendCommand(ctx context.Context, sessionID string, action CommandAction, payload json.RawMessage) (CommandResponse, error) {
	if c == nil {
		return CommandResponse{}, errors.New("SendCommand: nil client")
	}
	if sessionID == "" {
		return CommandResponse{}, errors.New("SendCommand: empty sessionID")
	}
	if action == "" {
		return CommandResponse{}, errors.New("SendCommand: empty action")
	}
	dialTimeout := DefaultStreamDialTimeout
	if deadline, ok := ctx.Deadline(); ok {
		if d := time.Until(deadline); d > 0 && d < dialTimeout {
			dialTimeout = d
		}
	}
	u, err := url.Parse(c.BaseURL)
	if err != nil {
		return CommandResponse{}, fmt.Errorf("SendCommand: parse base url: %w", err)
	}
	switch u.Scheme {
	case "http":
		u.Scheme = "ws"
	case "https":
		u.Scheme = "wss"
	case "ws", "wss":
		// already a WS URL — keep as-is
	default:
		return CommandResponse{}, fmt.Errorf("SendCommand: unsupported base url scheme %q", u.Scheme)
	}
	u.Path = "/v1/sessions/" + sessionID + "/command"
	q := u.Query()
	q.Set("action", string(action))
	u.RawQuery = q.Encode()

	dialCtx, cancel := context.WithTimeout(ctx, dialTimeout)
	defer cancel()

	dialer := *websocket.DefaultDialer
	dialer.HandshakeTimeout = dialTimeout
	conn, resp, err := dialer.DialContext(dialCtx, u.String(), http.Header{
		"User-Agent": []string{"bbl-loop/6d-c'-B"},
	})
	if err != nil {
		if resp != nil {
			return CommandResponse{}, fmt.Errorf("SendCommand: dial %s: %w (status %d)", u.String(), err, resp.StatusCode)
		}
		return CommandResponse{}, fmt.Errorf("SendCommand: dial %s: %w", u.String(), err)
	}
	defer conn.Close()

	// Build + send the request frame. RequestID is
	// timestamp + 4-byte rand suffix — enough entropy to
	// keep concurrent requests from colliding for the
	// lifetime of a single TUI session.
	req := CommandRequest{
		Type:      "command",
		RequestID: newRequestID(),
		Action:    action,
		SessionID: sessionID,
		Payload:   payload,
	}
	if err := conn.WriteJSON(req); err != nil {
		return CommandResponse{}, fmt.Errorf("SendCommand: write request: %w", err)
	}

	// Read exactly one response frame. The server is
	// expected to close the socket after the response;
	// we don't loop. ReadMessage respects the connection
	// deadline so a stuck server can't hold the caller
	// forever.
	if err := conn.SetReadDeadline(time.Now().Add(dialTimeout)); err != nil {
		return CommandResponse{}, fmt.Errorf("SendCommand: set read deadline: %w", err)
	}
	_, raw, err := conn.ReadMessage()
	if err != nil {
		return CommandResponse{}, fmt.Errorf("SendCommand: read response: %w", err)
	}
	var resp2 CommandResponse
	if err := json.Unmarshal(raw, &resp2); err != nil {
		return CommandResponse{}, fmt.Errorf("SendCommand: unmarshal response: %w", err)
	}
	if resp2.RequestID != req.RequestID {
		// Server echoed a different requestId — should
		// not happen, but we surface rather than
		// silently mis-correlate. The caller's fallback
		// path is the HTTP route.
		return resp2, fmt.Errorf("SendCommand: requestId mismatch: sent %q got %q", req.RequestID, resp2.RequestID)
	}
	return resp2, nil
}
